stages:
# Add bordering at continent edge.
  - type: REPLACE_LIST
    sampler:
      type: EXPRESSION
      #Expand range to nominal -1 to 1
      expression: (continents(x, z)*2-1)
    default-from: ARID_PALE_GARDEN
    default-to:
      - ARID_PALE_GARDEN_COAST: &coastalWeight 5
      - SELF: &notCoast 95
    to:
      ORANGE_ARID_PALE_GARDEN:
      - ORANGE_ARID_PALE_GARDEN_COAST: *coastalWeight
      - SELF: *notCoast