stages:
#  - type: REPLACE
#    from: _non_spot
#    to:
#      - ocean: 1
#      - land: 1
#    sampler:
#      type: EXPRESSION
#      expression: continentalDistribution(x, z)

  #land spot
  - type: REPLACE
    from: _land_spot
    to:
      - volcano: 1
      #- mesa: 1
      - sinkhole: 1
    sampler:
      type: EXPRESSION
      expression: spotSizePercent(x, z)*2-1

  #ocean spot
  - type: REPLACE
    from: _ocean_spot
    to:
      - volcano: 1
      - mesa: 1
    sampler:
      type: EXPRESSION
      expression: spotSizePercent(x, z)*2-1

  - type: REPLACE
    from: volcano
    to:
      #- extinct-volcano: 5
      - active-volcano: 1
    sampler:
      type: EXPRESSION
      expression: volcanoActivity(x, z)

  - type: REPLACE
    from: extinct-volcano
    to:
      - extinct-volcano: 4
      # - crater-lake: 1 # Crater lakes are disabled until a good method of adding fluid is implemented
    sampler:
      type: EXPRESSION
      expression: spotEdgeRadiusPercent(x, z)*2-1

  - type: REPLACE
    from: active-volcano
    to:
      - live-volcano: 4
      - PRISMATIC_SPRING: 1
    sampler:
      type: EXPRESSION
      expression: spotEdgeRadiusPercent(x, z)*2-1

  - type: BORDER
    from: live-volcano
    replace: ocean
    to:
      - ocean: 1
      - volcano-coast: 1
    sampler:
      type: EXPRESSION
      expression: nearSpot(x, z)
      variables: $math/samplers/spots.yml:variables

  - type: BORDER
    from: sinkhole
    replace: land
    to: sinkhole-border
    sampler:
      type: CONSTANT

  - type: BORDER
    from: sinkhole
    replace: ocean
    to: sinkhole-border-ocean
    sampler:
      type: CONSTANT