variationSampler: &variationSampler
  type: CELLULAR
  return: CellValue
  frequency: 1 / 100 / ${customization.yml:variation-scale} / ${customization.yml:global-scale}

# Tags are used by biomes to determine the kind of trench to use, except for biomes with
# their own specific trench biome.

stages:
  # Regular trenches
  - type: REPLACE_LIST
    default-from: USE_TRENCH
    default-to:
      - SELF: 1
      - OCEAN_TRENCH: 1
    to:
      DEEP_DEPTHS:
        - SELF: 1
        - DEEP_DEPTHS_TRENCH: 1
    sampler:
      dimensions: 2
      type: EXPRESSION
      expression: trenchSampler(x,z)
  - type: REPLACE_LIST
    default-from: USE_COLD_TRENCH
    default-to:
      - SELF: 1
      - COLD_OCEAN_TRENCH: 1
    to:
      COLD_DEEP_DEPTHS:
        - SELF: 1
        - COLD_DEEP_DEPTHS_TRENCH: 1
    sampler:
      dimensions: 2
      type: EXPRESSION
      expression: trenchSampler(x,z)
  - type: REPLACE_LIST
    default-from: USE_FROZEN_TRENCH
    default-to:
      - SELF: 1
      - FROZEN_OCEAN_TRENCH: 1
    to:
      FROZEN_DEEP_DEPTHS:
        - SELF: 1
        - FROZEN_DEEP_DEPTHS_TRENCH: 1
    sampler:
      dimensions: 2
      type: EXPRESSION
      expression: trenchSampler(x,z)
  - type: REPLACE_LIST
    default-from: USE_TROPICAL_TRENCH
    default-to:
      - SELF: 1
      - TROPICAL_OCEAN_TRENCH: 1
    to:
      TROPICAL_DEEP_DEPTHS:
        - SELF: 1
        - TROPICAL_DEEP_DEPTHS_TRENCH: 1
    sampler:
      dimensions: 2
      type: EXPRESSION
      expression: trenchSampler(x,z)
  - type: REPLACE_LIST
    default-from: USE_SUBTROPICAL_TRENCH
    default-to:
      - SELF: 1
      - SUBTROPICAL_OCEAN_TRENCH: 1
    to:
      SUBTROPICAL_DEEP_DEPTHS:
        - SELF: 1
        - SUBTROPICAL_DEEP_DEPTHS_TRENCH: 1
    sampler:
      dimensions: 2
      type: EXPRESSION
      expression: trenchSampler(x,z)
  - type: REPLACE
    from: USE_CORAL_TRENCH
    to:
      - SELF: 1
      - CORAL_OCEAN_TRENCH: 1
    sampler:
      dimensions: 2
      type: EXPRESSION
      expression: trenchSampler(x,z)

  - type: REPLACE_LIST
    default-from: OCEAN_TRENCH
    default-to:
      - SELF: 2
      - DEEP_OCEAN_VENTS: 1
    to:
      COLD_OCEAN_TRENCH:
        - SELF: 2
        - COLD_DEEP_OCEAN_VENTS: 1
      FROZEN_OCEAN_TRENCH:
        - SELF: 2
        - FROZEN_DEEP_OCEAN_VENTS: 1
      SUBTROPICAL_OCEAN_TRENCH:
        - SELF: 2
        - SUBTROPICAL_DEEP_OCEAN_VENTS: 1
      TROPICAL_OCEAN_TRENCH:
        - SELF: 2
        - TROPICAL_DEEP_OCEAN_VENTS: 1
    sampler: *variationSampler