stages:
#  - type: REPLACE
#    from: _non_spot
#    to:
#      - ocean: 1
#      - land: 1
#    sampler:
#      type: EXPRESSION
#      expression: continentalDistribution(x, z)

  #land spot
  - type: REPLACE
    from: _land_spot
    to:
      - PRISMATIC_SPRING: 2
      - SELF: 11
    sampler:
      type: EXPRESSION
      expression: spotSizePercent(x, z)*2-1

  #ocean spot
  - type: REPLACE
    from: _ocean_spot
    to:
      - PRISMATIC_SPRING: 2
      - SELF: 11
    sampler:
      type: EXPRESSION
      expression: spotSizePercent(x, z)*2-1

  - type: REPLACE
    from: _land_spot
    to:
      - sinkhole: 4
      - live-volcano: 3
      - extinct-volcano: 4
    sampler:
      type: EXPRESSION
      expression: volcanoActivity(x, z)
      
  #ocean spot
  - type: REPLACE
    from: _ocean_spot
    to:
      - live-volcano: 3
      - extinct-volcano: 4
    sampler:
      type: EXPRESSION
      expression: volcanoActivity(x, z)

  - type: BORDER
    from: live-volcano
    replace: ocean
    to:
      - ocean: 1
      - volcano-coast: 1
    sampler:
      type: CONSTANT

  - type: BORDER
    from: sinkhole
    replace: land
    to: sinkhole-border
    sampler:
      type: CONSTANT

  - type: BORDER
    from: sinkhole
    replace: ocean
    to: sinkhole-border-ocean
    sampler:
      type: CONSTANT

  - type: BORDER
    from: extinct-volcano
    replace: ocean
    to: sinkhole-border-ocean
    sampler:
      type: CONSTANT