stages:
  - type: REPLACE
    from: ALL
    to:
      - SELF: 2
      - spot: 1
    sampler:
      type: EXPRESSION
      expression: if(spotDistance(x, z) < spotRadius(x, z) + biomeBorder, 1, -1)
      variables: $math/samplers/spots.yml:variables

  - type: REPLACE
    from: spot
    to:
      - extinct-volcano: 20
      - crater-lake: 5
      - live-volcano: 4
      - PRISMATIC_SPRING: 1
      - mesa: 25
    sampler:
      type: EXPRESSION
      expression: spotSizePercent(x, z)*2-1