#riverSampler: &riverSampler
#  type: EXPRESSION
#  expression: |
#    riverSampler(x,z)

# Tags are used by biomes to determine the kind of river to use, except for biomes with
# their own specific river biome. These tags are formatted by the type of river, and optionally
# the type of river wetlands surrounding the river, e.g USE_FROZEN_RIVER_FROZEN_MARSH would mean
# the biome will use a frozen river with frozen marshes surrounding it.

stages:
  # Regular rivers
  - type: REPLACE_LIST
    default-from: USE_RIVER
    default-to:
      - SELF: 1
      - RIVER: 1
    to:
      # Biome specific rivers
      TEMPERATE_MOUNTAINS:
        - SELF: 1
        - TEMPERATE_MOUNTAINS_RIVER: 1
      HIGHLANDS:
        - SELF: 1
        - HIGHLANDS_RIVER: 1
      MOUNTAINS:
        - SELF: 1
        - MOUNTAINS_RIVER: 1
      XERIC_MOUNTAINS:
        - SELF: 1
        - XERIC_MOUNTAINS_RIVER: 1
      RED_XERIC_MOUNTAINS:
        - SELF: 1
        - RED_XERIC_MOUNTAINS_RIVER: 1
      ORANGE_XERIC_MOUNTAINS:
        - SELF: 1
        - ORANGE_XERIC_MOUNTAINS_RIVER: 1
      BADLANDS:
        - SELF: 1
        - BADLANDS_RIVER: 1
      DRY_TEMPERATE_MOUNTAINS:
        - SELF: 1
        - DRY_TEMPERATE_MOUNTAINS_RIVER: 1
      DRY_TEMPERATE_WHITE_MOUNTAINS:
        - SELF: 1
        - DRY_TEMPERATE_WHITE_MOUNTAINS_RIVER: 1
      SNOWY_MOUNTAINS:
        - SELF: 1
        - SNOWY_MOUNTAINS_RIVER: 1
      SNOWY_TUFF_MOUNTAINS:
        - SELF: 1
        - SNOWY_TUFF_MOUNTAINS_RIVER: 1
      SNOWY_BLACKSTONE_MOUNTAINS:
        - SELF: 1
        - SNOWY_BLACKSTONE_MOUNTAINS_RIVER: 1
      TRAVERTINE_TERRACES:
        - SELF: 1
        - TRAVERTINE_TERRACES_RIVER: 1
      ALPINE_ASCENDANCY:
        - SELF: 1
        - ALPINE_ASCENDANCY_RIVER: 1
      BADLANDS_BALCONIES:
        - SELF: 1
        - BAD_BALCOONIES_RIVER: 1
      FROZEN_FUNGI:
        - SELF: 1
        - FROZEN_FUNGI_RIVER: 1
      GLOOMY_GORGE:
        - SELF: 1
        - GLOOMY_GORGE_RIVER: 1
      LUSH_LOOPS: #USE_LOOPS_RIVER:
        - SELF: 1
        - LOOPS_RIVER: 1
      MOUNTAIN_MIRRORS:
        - SELF: 1
        - MOUNTAIN_MIRRORS_RIVER: 1
      SCARLET_SANCTUARY:
        - SELF: 1
        - SCARLET_SANCTUARY_RIVER: 1
      SWAMP:
        - SELF: 1
        - SWAMP_RIVER: 1
      VERDANT_VALLEYS: #USE_VERDANT_RIVER:
        - SELF: 1
        - VERDANT_RIVER: 1
      VERTICAL_VISTAS:
        - SELF: 1
        - VISTAS_RIVER: 1
      VERTICAL_VISTAS_WARM:
        - SELF: 1
        - VERTICAL_JUNGLE_RIVER: 1
      VERTICAL_VISTAS_FROZEN:
        - SELF: 1
        - MOUNTAIN_MIRRORS_RIVER: 1

    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # Desert rivers
  - type: REPLACE
    from: USE_DESERT_RIVER
    to:
      - SELF: 1
      - GALLERY_FOREST: 1
      - DESERT_RIVER: 2
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # Red desert rivers
  - type: REPLACE
    from: USE_RED_DESERT_RIVER
    to:
      - SELF: 1
      - RED_GALLERY_FOREST: 1
      - RED_DESERT_RIVER: 2
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # Orange desert rivers
  - type: REPLACE
    from: USE_ORANGE_DESERT_RIVER
    to:
      - SELF: 1
      - ORANGE_GALLERY_FOREST: 1
      - ORANGE_DESERT_RIVER: 2
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # Tar pit rivers
  - type: REPLACE
    from: USE_TAR_PIT_RIVER
    to:
      - SELF: 1
      - TAR_PIT_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # Regular rivers with temperate marshes
  # SUPPRESSED - Only marshes directly get a river replacement, no need to bound other biomes with marshland which
  # forces elevation change.
  - type: REPLACE
    from: USE_RIVER_TEMPERATE_MARSH
    to:
      - SELF: 1
      - RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # Pale Garden rivers
  - type: REPLACE
    from: USE_PALE_GARDEN_RIVER
    to:
      - SELF: 1
      - PALE_GARDEN_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  - type: REPLACE
    from: USE_ARID_PALE_GARDEN_RIVER
    to:
      - SELF: 1
      - ARID_PALE_GARDEN_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  - type: REPLACE
    from: USE_ORANGE_ARID_PALE_GARDEN_RIVER
    to:
      - SELF: 1
      - ORANGE_ARID_PALE_GARDEN_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  - type: REPLACE
    from: USE_RED_ARID_PALE_GARDEN_RIVER
    to:
      - SELF: 1
      - RED_ARID_PALE_GARDEN_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # Pale Garden rivers
  - type: REPLACE
    from: USE_POLAR_PALE_GARDEN_RIVER
    to:
      - SELF: 1
      - POLAR_PALE_GARDEN_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  - type: REPLACE
    from: USE_MUSHROOM_RIVER
    to:
      - SELF: 1
      - MUSHROOM_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  - type: REPLACE
    from: USE_POLAR_MUSHROOM_RIVER
    to:
      - SELF: 1
      - POLAR_MUSHROOM_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # Regular rivers with bordering swamps
  - type: REPLACE
    from: USE_RIVER_TEMPERATE_SWAMP
    to:
      - SELF: 1
      - SWAMP: 1
      - RIVER: 2
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # Warm rivers
  - type: REPLACE
    from: USE_LUKEWARM_RIVER
    to:
      - SELF: 1
      - LUKEWARM_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # Tropical rivers
  - type: REPLACE
    from: USE_TROPICAL_RIVER
    to:
      - SELF: 1
      - GALLERY_FOREST: 1
      - TROPICAL_RIVER: 2
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # Tropical coastal rivers with mangrove swamps
  - type: REPLACE
    from: USE_RIVER_COASTAL_TROPICAL_SWAMP
    to:
      - SELF: 1
      - MANGROVE_SWAMP: 1
      - TROPICAL_RIVER: 2
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # Cold rivers
  - type: REPLACE
    from: USE_COLD_RIVER
    to:
      - SELF: 1
      - COLD_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # Frozen Rivers
  - type: REPLACE
    from: USE_FROZEN_RIVER
    to:
      - SELF: 1
      - FROZEN_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  - type: REPLACE
    from: USE_LAND_GLACIER_RIVER
    to:
      - SELF: 1
      - LAND_GLACIER_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # Frozen rivers with frozen marshes
  - type: REPLACE
    from: USE_FROZEN_RIVER_FROZEN_MARSH
    to:
      - SELF: 1
      - FROZEN_MARSH: 1
      - FROZEN_RIVER: 2
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # 
  - type: REPLACE
    from: USE_JUNGLE_VISTA_RIVER
    to:
      - SELF: 1
      - VERTICAL_JUNGLE_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # 
  - type: REPLACE
    from: USE_FROZEN_VISTA_RIVER
    to:
      - SELF: 1
      - MOUNTAIN_MIRRORS_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # 
  #- type: REPLACE
  #  from: USE_JUNGLE_VISTA_RIVER
  #  to:
  #    - SELF: 1
  #    - VISTAS_RIVER: 1
  #  sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # 
  - type: REPLACE
    from: USE_VERDANT_RIVER
    to:
      - SELF: 1
      - VERDANT_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # 
  - type: REPLACE
    from: USE_LOOPS_RIVER
    to:
      - SELF: 1
      - LOOPS_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # 
  - type: REPLACE
    from: USE_DRAFTY_STREAM_RIVER
    to:
      - SELF: 1
      - DRAFTY_STREAM_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # 
  - type: REPLACE
    from: USE_FROSTBITE_RIVERS
    to:
      - SELF: 1
      - FROSTBITE_RIVERS: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # 
  - type: REPLACE
    from: USE_CHILLY_CREEK_RIVER
    to:
      - SELF: 1
      - CHILLY_CREEK_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # 
  - type: REPLACE
    from: USE_SWAMP_RIVER
    to:
      - SELF: 1
      - SWAMP_RIVER: 1
    sampler: $math/samplers/rivers.yml:samplers.riverSampler
  # 
  #- type: REPLACE
  #  from: USE_DRAFTY_STREAMS
  #  to:
  #    - SELF: 1
  #    - SWAMP_RIVER: 1
  #  sampler: $math/samplers/rivers.yml:samplers.riverSampler

    