stages:
  - type: REPLACE
    from: land
    sampler:
      dimensions: 2
      type: DOMAIN_WARP #Tried with A = 400, warp freq = 0.001, lots of overlap
      amplitude: 60 
      warp:
        type: OPEN_SIMPLEX_2
        frequency: 0.002
      sampler:
        type: CELLULAR
        return: CellValue
        frequency: 1 /  ${customization.yml:biomeSpread.regionDistance}
    to:
      p1: 1
      p2: 1
      p3: 5
  - type: REPLACE
    from: ocean
    sampler:
      dimensions: 2
      type: DOMAIN_WARP
      amplitude: 60 
      warp:
        type: OPEN_SIMPLEX_2
        frequency: 0.002
      sampler:
        type: CELLULAR
        return: CellValue
        frequency: 1 /  ${customization.yml:biomeSpread.islandDistance}
    to:
      ocean: 30
      o1: 1
      ocean: 30