stages:
  - type: REPLACE
    sampler:
      type: CONSTANT
    from: land
    to: 
      ASPEN_FOREST : 1
  - type: REPLACE_LIST
    sampler:
      type: CONSTANT
    default-from: coast
    default-to: DESERT
    to:
      land: DRY_FIR_FIELDS
      ocean: OCEAN
      vast-forest: BLACK_FOREST
      island: MUSHROOM_FIELDS
      crater-lake: TROPICAL_CRATER_LAKE
      live-volcano: ERUPTED_VOLCANO
      extinct-volcano: TROPICAL_EXTINCT_VOLCANO
      mesa: TROPICAL_MESA
      volcano-coast: MUDDY_COASTS
      coast_wide: ORANGE_DESERT
      coast_small: RED_DESERT
      p1: ALIEN_MARSH
      p2: BADLANDS
      p3: BAMBOO_JUNGLE
      p4: FROSTY_FINGERS
      p5: PRAIRIE
      l1: VARIANT_C
      l2: VARIANT_F
      l3: VARIANT_G
      l4: VARIANT_H
      l5: FIRMIHIN_FOREST
      o1: DEEP_OCEAN
      o2: FROZEN_OCEAN
      o3: SHALLOW_CORAL_OCEAN
      o4: OCEAN_TRENCH
      o5: ICEBERG_OCEAN
      _cold_canyon: FROZEN_MARSH
      _warm_canyon: SAVANNA
      land-sea-border: BARE_BOULDERFIELDS
      vast-forest-coast: PALE_GARDEN_COAST
      island-coast: COAST_MEDIUM_A
      sinkhole: YELLOWSTONE
      sinkhole-border-ocean: SINKHOLE_OUTER
      sinkhole-border-land: SINKHOLE_OUTER
      sinkhole-border: TEMPERATE_SINKHOLE_BORDER