stages:
  - type: REPLACE
    sampler:
      type: CELLULAR
      jitter: ${customization.yml:biomeSpread.cellJitter}
      return: CellValue
      frequency: 5 / ${customization.yml:biomeSpread.cellDistance}
    from: land
    to: 
      ALIEN_MARSH : 1
      ALPINE_ASCENDANCY : 1
      ARCHIPELAGO : 1
      ARCTIC_ARCHES : 1
      ARCTIC_MESA : 1
      ARID_ARBORETUM : 1
      ARID_PALE_GARDEN : 1
      ARID_PALE_GARDEN_COAST : 1
      ARID_SPIKES : 1
      ASPEN_FOREST : 1
      AUTUMNAL_WOODLANDS : 1
      AZALEA_FOREST : 1
      BADLANDS : 1
      BADLANDS_BALCONIES : 1
      BADLANDS_BUTTES : 1
      BAMBOO_BASIN : 1
      BAMBOO_JUNGLE : 1
      BARE_BOULDERFIELDS : 1
      BEACH : 1
      BIRCH_FOREST : 1
      BIRCH_WOODLANDS : 1
      BITTER_HEIGHTS : 1
      BLACK_FOREST : 1
      BLACK_SAND_BEACH : 1
      BOREAL_CRATER_LAKE : 1
      BOREAL_EXTINCT_VOLCANO : 1
      BOREAL_MESA : 1
      BOREAL_SHRUBLAND : 1
      BROADLEAF_FOREST : 1
      CANOPY_CASCADES : 1
      CARVING_CREAKS : 1
      CHAPARRAL : 1
      CHILLY_CREEKS : 1
      CLOUD_FOREST : 1
      COAST_COLD_A : 1
      COAST_COLD_B : 1
      COAST_MEDIUM_A : 1
      COAST_MEDIUM_B : 1
      COAST_WARM_A : 1
      COAST_WARM_B : 1
      COLD_CRATER_LAKE : 1
      COLD_DESERT_MESA : 1
      COLD_EXTINCT_VOLCANO : 1
      COLD_ISLAND_SHALLOWS : 1
      COLD_STEPPE : 1
      DARK_FOREST : 1
      DARK_OAK_WOODLANDS : 1
      DENSELY_WOODED_HIGHLANDS : 1
      DESERT : 1
      DESERT_CRATER_LAKE : 1
      DESERT_EXTINCT_VOLCANO : 1
      DESERT_MESA : 1
      DESERT_PILLARS : 1
      DESERT_SPIKES : 1
      DESERT_SPIKES_GOLD : 1
      DESERT_TERRACES : 1
      DIKSAM_PLATEAU : 1
      DRAFTY_STREAMS : 1
      DRY_FIR_FIELDS : 1
      DRY_PALM_FOREST : 1
      DRY_TEMPERATE_MOUNTAINS : 1
      DRY_TEMPERATE_WHITE_MOUNTAINS : 1
      DRY_WOODLANDS : 1
      DRYBRUSH : 1
      ENCHANTED_WOODLANDS : 1
      ERUPTED_VOLCANO : 1
      FIR_FIELDS : 1
      FIR_HIGHLANDS : 1
      FIRMIHIN_FOREST : 1
      FLOWERING_FOREST : 1
      FOLIAGE_FORTRESS_INNER : 1
      FOLIAGE_FORTRESS_MIDDLE : 1
      FOLIAGE_FORTRESS_OUTER : 1
      FOSSILIZED_FENLANDS : 1
      FRIGID_WASTELANDS : 1
      FROSTBOUND_CHASMS : 1
      FROSTCOATED_BOG : 1
      FROSTY_FINGERS : 1
      FROZEN_ARCHIPELAGO : 1
      FROZEN_BEACH : 1
      FROZEN_FUNGI : 1
      FROZEN_ISLAND_SHALLOWS : 1
      FROZEN_MARSH : 1
      FROZEN_SPIRES : 1
      GALLERY_FOREST : 1
      GLACIAL_OVERHANGS : 1
      GLOOMY_GORGE : 1
      GRASS_SAVANNA : 1
      HIGHLANDS : 1
      ICE_CAPS : 1
      ICE_SPIKES : 1
      ICEBOUND_JUNGLE : 1
      ICY_INCISIONS : 1
      ISLAND_SHALLOWS : 1
      JUNGLE : 1
      LAND_COLD_A : 1
      LAND_COLD_B : 1
      LAND_GLACIER : 1
      LAND_MEDIUM_A : 1
      LAND_MEDIUM_B : 1
      LAND_WARM_A : 1
      LAND_WARM_B : 1
      LAVENDER_CRAGS : 1
      LAVENDER_FIELDS : 1
      LUSH_LOOPS : 1
      MANGROVE_SWAMP : 1
      MAPLE_GROVE : 1
      MAPLE_WOODLANDS : 1
      MARINE_MONOLITHS : 1
      MARSH : 1
      MESA_MONUMENTS : 1
      MONSOON_FOREST : 1
      MONTANE_FOREST : 1
      MOORLAND : 1
      MOUNTAIN_MIRRORS : 1
      MOUNTAINS : 1
      MUDDY_COASTS : 1
      MURKY_MARSHLANDS : 1
      MUSHROOM_COAST : 1
      MUSHROOM_FIELDS : 1
      MUSKEG : 1
      OAK_FOREST : 1
      OAK_SAVANNA : 1
      OAK_WOODLANDS : 1
      OASIS : 1
      OLD_GROWTH_SEQUOIA_FOREST : 1
      ORANGE_ARID_PALE_GARDEN : 1
      ORANGE_ARID_PALE_GARDEN_COAST : 1
      ORANGE_DESERT : 1
      ORANGE_DRY_PALM_FOREST : 1
      ORANGE_GALLERY_FOREST : 1
      ORANGE_XERIC_MOUNTAINS : 1
      ORANGE_XERIC_SHRUBLAND : 1
      OVERGROWN_CLIFFS : 1
      PALE_GARDEN : 1
      PALE_GARDEN_COAST : 1
      PALM_BEACH : 1
      PALM_FOREST : 1
      PEARLESCENT_DESERT : 1
      PERMAFROST_CLIFFS : 1
      PILLOW_PLAINS_INNER : 1
      PILLOW_PLAINS_MIDDLE : 1
      PILLOW_PLAINS_OUTER : 1
      PINE_BARRENS : 1
      PINE_CANOPY : 1
      POLAR_MUSHROOM_COAST : 1
      POLAR_MUSHROOM_FIELDS : 1
      POLAR_PALE_GARDEN : 1
      POLAR_PALE_GARDEN_COAST : 1
      PRAIRIE : 1
      PRISMATIC_SPRING : 1
      RED_ARID_PALE_GARDEN : 1
      RED_ARID_PALE_GARDEN_COAST : 1
      RED_DESERT : 1
      RED_DRY_PALM_FOREST : 1
      RED_GALLERY_FOREST : 1
      RED_MAPLE_GROVE : 1
      RED_XERIC_MOUNTAINS : 1
      RED_XERIC_SHRUBLAND : 1
      REDWOOD_WOODLANDS : 1
      ROCKY_ARCHIPELAGO : 1
      ROCKY_DESERT : 1
      ROCKY_GRASSLAND : 1
      ROCKY_JUNGLE : 1
      ROCKY_REFUGE : 1
      SAKURA_GROVE : 1
      SAKURA_STREAMS : 1
      SAKURA_WOODLANDS : 1
      SALT_FLATS : 1
      SANDSTONE_ARCHIPELAGO : 1
      SANDY_SPLITS : 1
      SAVANNA : 1
      SAVANNA_OVERHANGS : 1
      SCARLET_SANCTUARY : 1
      SECLUDED_VALLEY : 1
      SECLUDED_VALLEY_OUTER : 1
      SEQUOIA_FOREST : 1
      SHALE_BEACH : 1
      SHRUB_BEACH : 1
      SINKHOLE_FOREST : 1
      SINKHOLE_FROZEN : 1
      SINKHOLE_JUNGLE : 1
      SINKHOLE_OUTER : 1
      SNOWDRIFT_COASTS : 1
      SNOWSWEPT_MEADOWS : 1
      SNOWY_BADLANDS : 1
      SNOWY_BIRCH_FOREST : 1
      SNOWY_BLACKSTONE_MOUNTAINS : 1
      SNOWY_DUNES : 1
      SNOWY_MEADOW : 1
      SNOWY_MOUNTAINS : 1
      SNOWY_PLAINS : 1
      SNOWY_SPIRES : 1
      SNOWY_TAIGA : 1
      SNOWY_TUFF_MOUNTAINS : 1
      SPRUCE_WOODLANDS : 1
      STEPPE : 1
      SUBTROPICAL_ISLAND_SHALLOWS : 1
      SUGAR_PINE_WOODLANDS : 1
      SUNFLOWER_PRAIRIE : 1
      SWAMP : 1
      TAIGA : 1
      TAIGA_CLEARING : 1
      TALL_TIMBERLAND : 1
      TAR_PITS : 1
      TEMPERATE_ALPHA_MOUNTAINS : 1
      TEMPERATE_CRATER_LAKE : 1
      TEMPERATE_EXTINCT_VOLCANO : 1
      TEMPERATE_GRASSLAND : 1
      TEMPERATE_MESA : 1
      TEMPERATE_MONTANE_RAINFOREST : 1
      TEMPERATE_MOUNTAINS : 1
      TEMPERATE_OVERPASS : 1
      TEMPERATE_RAINFOREST : 1
      TRAVERTINE_TERRACES : 1
      TROPICAL_CRATER_LAKE : 1
      TROPICAL_EXTINCT_VOLCANO : 1
      TROPICAL_FLOODPLAIN : 1
      TROPICAL_ISLAND_SHALLOWS : 1
      TROPICAL_MESA : 1
      TROPICAL_MUSHROOM_COAST : 1
      TROPICAL_MUSHROOM_FIELDS : 1
      TROPICAL_RAINFOREST : 1
      TUNDRA : 1
      TUNDRA_TRACKS : 1
      VARIANT_C : 1
      VARIANT_F : 1
      VARIANT_G : 1
      VARIANT_H : 1
      VERDANT_VALLEYS : 1
      VERTICAL_VISTAS : 1
      WATERY_WILDS : 1
      WET_SAVANNA : 1
      WHITE_WALLOWS : 1
      WINTRY_WATERS : 1
      WOODED_BUTTES : 1
      XERIC_MOUNTAINS : 1
      XERIC_SHRUBLAND : 1
      YELLOW_MAPLE_GROVE : 1
      YELLOWSTONE :  1

  - type: REPLACE_LIST
    sampler:
      type: CONSTANT
    default-from: coast
    default-to: DESERT
    to:
      land: DRY_FIR_FIELDS
      ocean: OCEAN
      vast-forest: BLACK_FOREST
      island: MUSHROOM_FIELDS
      crater-lake: TROPICAL_CRATER_LAKE
      live-volcano: ERUPTED_VOLCANO
      extinct-volcano: TROPICAL_EXTINCT_VOLCANO
      mesa: TROPICAL_MESA
      volcano-coast: MUDDY_COASTS
      coast_wide: ORANGE_DESERT
      coast_small: RED_DESERT
      p1: ALIEN_MARSH
      p2: BADLANDS
      p3: BAMBOO_JUNGLE
      p4: FROSTY_FINGERS
      p5: PRAIRIE
      l1: VARIANT_C
      l2: VARIANT_F
      l3: VARIANT_G
      l4: VARIANT_H
      l5: FIRMIHIN_FOREST
      o1: DEEP_OCEAN
      o2: FROZEN_OCEAN
      o3: SHALLOW_CORAL_OCEAN
      o4: OCEAN_TRENCH
      o5: ICEBERG_OCEAN
      _cold_canyon: FROZEN_MARSH
      _warm_canyon: SAVANNA
      land-sea-border: BARE_BOULDERFIELDS
      vast-forest-coast: PALE_GARDEN_COAST
      island-coast: COAST_MEDIUM_A
      sinkhole: YELLOWSTONE
      sinkhole-border-ocean: SINKHOLE_OUTER
      sinkhole-border-land: SINKHOLE_OUTER
      sinkhole-border: TEMPERATE_SINKHOLE_BORDER