stages:
# Consider BiomeShapeLandmassDist2Center
  - type: REPLACE
    from: _secluded_valleys
    sampler:
      dimensions: 2
      type: EXPRESSION
      expression: smallBiomeSmallCenterDist(x, z)
    to: # 0 = outer, 1 = inner
      SECLUDED_VALLEY_OUTER: 1
      SECLUDED_VALLEY: 1
  #- type: REPLACE
  #  from: _verdant_valleys
  #  sampler:
  #    dimensions: 2
  #    type: EXPRESSION
  #    expression: smallBiomeSmallCenterDist(x, z)
  #  to: # 0 = outer, 1 = inner
  #    VERDANT_VALLEYS_OUTER: 2
  #    VERDANT_VALLEYS: 1
  - type: REPLACE
    from: _pillow_plains
    sampler:
      dimensions: 2
      type: EXPRESSION
      expression: smallBiomeWideCenterDist(x, z)
      variables:
        valley_srt: $customization.yml:valley-srt
        valley_dist: $customization.yml:valley-dist
      #expression: |
      #  if(normDistIntoBiome(x,z)<((1+valley_srt)/2), -1,
      #    if(normDistIntoBiome(x,z)<valley_srt, 0, 1))
    to: # 0 = outer, 1 = inner
      PILLOW_PLAINS_OUTER: 1
      PILLOW_PLAINS_MIDDLE: 1
      PILLOW_PLAINS_INNER: 1

  - type: REPLACE
    from: _desert
    sampler:
      dimensions: 2
      type: EXPRESSION
      expression: smallBiomeSmallCenterDist(x, z)
    to: # 0 = outer, 1 = inner
      OASIS_OUTER: 2
      OASIS: 1
  - type: REPLACE
    from: _foliage_fortress
    sampler:
      dimensions: 2
      type: EXPRESSION
      variables:
        valley_srt: $customization.yml:valley-srt
        valley_dist: $customization.yml:valley-dist
      expression: smallBiomeSmallCenterDist(x, z)
      #expression: |
      #  if(normDistIntoBiome(x,z)<((1+valley_srt)/2), -1,
      #    if(normDistIntoBiome(x,z)<valley_srt, 0, 1))
    to: # 0 = outer, 1 = inner
      FOLIAGE_FORTRESS_OUTER: 1
      FOLIAGE_FORTRESS_MIDDLE: 1
      FOLIAGE_FORTRESS_INNER: 1