stages:

  - type: REPLACE
    from: _secluded_valleys
    sampler:
      dimensions: 2
      type: EXPRESSION
      variables: 
        valley_dist: $customization.yml:valley-dist
      expression: if(BiomeShapeLandmassDistance(x,z) < valley_dist, 1, -1)
    to: # 0 = outer, 1 = inner
      SECLUDED_VALLEY_OUTER: 1
      SECLUDED_VALLEY: 1
  - type: REPLACE
    from: _verdant_valleys
    sampler:
      dimensions: 2
      type: EXPRESSION
      variables: 
        valley_dist: $customization.yml:valley-dist
      expression: if(BiomeShapeLandmassDistance(x,z) < valley_dist, 1, -1)
    to: # 0 = outer, 1 = inner
      VERDANT_VALLEYS_OUTER: 1
      VERDANT_VALLEYS: 1
  - type: REPLACE
    from: _pillow_plains
    sampler:
      dimensions: 2
      type: EXPRESSION
      variables: 
        valley_dist: $customization.yml:valley-dist
      expression: |
        if(BiomeShapeLandmassDistance(x,z) < (valley_dist-0.2) , 1, 
          if(BiomeShapeLandmassDistance(x,z) < valley_dist, 0.5, -1))
    to: # 0 = outer, 1 = inner
      PILLOW_PLAINS_OUTER: 1
      PILLOW_PLAINS_MIDDLE: 1
      PILLOW_PLAINS_INNER: 1

  - type: REPLACE
    from: _desert
    sampler:
      dimensions: 2
      type: EXPRESSION
      variables: 
        valley_dist: $customization.yml:valley-dist
      expression: if(BiomeShapeLandmassDistance(x,z) < valley_dist, 1, -1)
    to: # 0 = outer, 1 = inner
      OASIS_OUTER: 1
      OASIS: 1
  - type: REPLACE
    from: _plateao
    sampler:
      dimensions: 2
      type: EXPRESSION
      variables: 
        edgeThreshold: ${customization.yml:biomeSpread.borderBiomes.edgeThreshold}
      expression: if(cells(x,z) < -edgeThreshold, 1, -1)
      samplers:
        cells:
          dimensions: 2
          type: CELLULAR
          jitter: ${customization.yml:biomeSpread.cellJitter}
          frequency: 1 / ${customization.yml:biomeSpread.cellDistance}
    to: # 0 = outer, 1 = inner
      FOLIAGE_FORTRESS_OUTER: 1
      _plateao_center: 1
  - type: REPLACE
    from: _plateao_center
    sampler:
      dimensions: 2
      type: EXPRESSION
      variables: 
        edgeThreshold: ${customization.yml:biomeSpread.borderBiomes.edgeThreshold}
      expression: if(cells(x,z) < -edgeThreshold - 0.08, 1, -1)
      samplers:
        cells:
          dimensions: 2
          type: CELLULAR
          jitter: ${customization.yml:biomeSpread.cellJitter}
          frequency: 1 / ${customization.yml:biomeSpread.cellDistance}
    to: # 0 = outer, 1 = inner
      FOLIAGE_FORTRESS_MIDDLE: 1
      FOLIAGE_FORTRESS_INNER: 1
