stages:
# Consider BiomeShapeLandmassDist2Center
  - type: REPLACE
    from: _secluded_valleys
    sampler:
      dimensions: 2
      type: EXPRESSION
      expression: dist2BiomeSegments(x, z)
    to: # 0 = outer, 1 = inner
      SECLUDED_VALLEY_OUTER: 2
      SECLUDED_VALLEY: 1
  - type: REPLACE
    from: _verdant_valleys
    sampler:
      dimensions: 2
      type: EXPRESSION
      expression: dist2BiomeSegments(x, z)
    to: # 0 = outer, 1 = inner
      VERDANT_VALLEYS_OUTER: 2
      VERDANT_VALLEYS: 1
  - type: REPLACE
    from: _pillow_plains
    sampler:
      dimensions: 2
      type: EXPRESSION
      expression: dist2BiomeSegments(x, z)
    to: # 0 = outer, 1 = inner
      PILLOW_PLAINS_OUTER: 1
      PILLOW_PLAINS_MIDDLE: 1
      PILLOW_PLAINS_INNER: 1

  - type: REPLACE
    from: _desert
    sampler:
      dimensions: 2
      type: EXPRESSION
      expression: dist2BiomeSegments(x, z)
    to: # 0 = outer, 1 = inner
      OASIS_OUTER: 2
      OASIS: 1
  - type: REPLACE
    from: _plateao
    sampler:
      dimensions: 2
      type: EXPRESSION
      expression: dist2BiomeSegments(x, z)
    to: # 0 = outer, 1 = inner
      FOLIAGE_FORTRESS_OUTER: 1
      FOLIAGE_FORTRESS_MIDDLE: 1
      FOLIAGE_FORTRESS_INNER: 1