stages: 
  #Restrict generation away from rivers
  - type: REPLACE
    sampler:
      type: EXPRESSION
      expression: if(continentalRiverDist(x, z)>=1,1,-1)
    from: land
    range:
      min: ${customization.yml:biomeSpread.canyons.minY}
      max: 319
    to:
      SELF: 1
      _pot_well: 1
      
  #Restrict generation away from spots
  - type: REPLACE
    sampler:
      type: EXPRESSION
      expression: nearSpot(x, z)
    from: _pot_well
    range:
      min: ${customization.yml:biomeSpread.canyons.minY}
      max: 319
    to:
      land: 1
      SELF: 1      

  #Distribute land into large temperature breaks to separate major canyon sections, since canyons changing vegitation mid trench is a little strange.
  - type: REPLACE
    sampler:
      type: EXPRESSION
      expression: temperature(x, z)
    from: _pot_well
    range:
      min: ${customization.yml:biomeSpread.canyons.minY}
      max: 319
    to:
      _cold_sinkhole: 3
      land: 1
      _mod_sinkhole: 3
      land: 1
      _warm_sinkhole: 3
     
      