stages:
  #Distribute land into large temperature breaks to seperate major canyon sections, since canyons changing vegitation mid trench is a little strange.
  - type: REPLACE
    sampler:
      type: EXPRESSION
      expression: temperature(x, z)
    from: land
    range:
      min: ${customization.yml:biomeSpread.canyons.minY}
      max: 319
    to:
      _cold_canyon: 8
      SELF: 3
      _warm_canyon: 8
      
  #Perform cellular distribution to create zones where canyons will actually occur so they are not everywhere in the land-mass.
  - type: REPLACE-LIST
    sampler:
      type: CELLULAR
      return: CellValue
    frequency: 1 / 500
    from: land
    range:
      min: ${customization.yml:biomeSpread.canyons.minY}
      max: 319
    default-from: _warm_canyon
    default-to:
      - SELF: &CanyonDist     1
      - land: &LandDist       3
    to:
      _cold_canyon:
        - SELF: *CanyonDist
        - land: *LandDist
      
  #Further contain the canyons so that they are not on the edge of biomes borders (like an ocean, which is very strange)
  - type: REPLACE-LIST
    sampler:
      dimensions: 2
      type: EXPRESSION
      variables: 
        edgeThreshold: ${customization.yml:biomeSpread.borderBiomes.edgeThreshold}
      expression: if(cells(x,z) < -edgeThreshold, 1, -1)
      samplers:
        cells:
          dimensions: 2
          type: CELLULAR
          jitter: ${customization.yml:biomeSpread.cellJitter}
          frequency: 1 / ${customization.yml:biomeSpread.cellDistance}
    default-from: _warm_canyon
    default-to: # 0 = outer, 1 = inner
      - land: &LandBorderDist     1
      - SELF: &CanyonCentDist     1
    to: # 0 = outer, 1 = inner
      _cold_canyon:
        - land: *LandBorderDist
        - SELF: *CanyonCentDist
        
  - type: REPLACE-LIST
    sampler:
      type: EXPRESSION
      dimensions: 2
      variables:
        canyonStrength: ${customization.yml:biomeSpread.canyons.canyonAmount}
      expression: |
        min(max(-mask(x,z * 1.3) - canyonStrength, 0) * 18, 1) *
        max((-abs(base(x,z)) + 0.3) * 2, 0) * (1 / 0.2)
      samplers:
        base:
          dimensions: 2
          type: OPEN_SIMPLEX_2S
          frequency: 1 / ${customization.yml:biomeSpread.cellDistance} * 1
        mask:
          dimensions: 2
          type: CELLULAR
          frequency: 1 / ${customization.yml:biomeSpread.cellDistance} * 0.15
          seed: 23456345
    range:
      min: ${customization.yml:biomeSpread.canyons.minY}
      max: 319
    default-from: _warm_canyon
    default-to: # 0 = outer, 1 = inner
      - land: &CanyonLandDist             16
      - SANDY_SPLITS: &CanyonFloorDist     9
    to: # 0 = outer, 1 = inner
      _cold_canyon:
      - land: &CanyonLandDist             16
      - ICY_INCISIONS: &CanyonFloorDist     9