stages:
  #Distribute land into large temperature breaks to seperate major canyon sections, since canyons changing vegitation mid trench is a little strange.
  - type: REPLACE
    sampler:
      dimensions: 2
      type: DOMAIN_WARP
      amplitude: 40 
      warp:
        type: OPEN_SIMPLEX_2
        frequency: 0.005
      sampler:
        type: EXPRESSION
        expression: temperature(x, z)      
    from: land
    range:
      min: ${customization.yml:biomeSpread.canyons.minY}
      max: 319
    to:
      _cold_canyon: 8
      SELF: 3
      _warm_canyon: 8