stages:
  #Distribute land into large temperature breaks to separate major canyon sections, since canyons changing vegitation mid trench is a little strange.
  - type: REPLACE
    sampler:
      type: EXPRESSION
      expression: if(continentalRiverDist(x, z)>=1,1,-1)
    from: land
    range:
      min: ${customization.yml:biomeSpread.canyons.minY}
      max: 319
    to:
      SELF: 1
      _pot_rift: 1
      
  #Restrict generation away from spots
  - type: REPLACE
    sampler:
      type: EXPRESSION
      expression: nearSpot(x, z)
    from: _pot_well
    range:
      min: ${customization.yml:biomeSpread.canyons.minY}
      max: 319
    to:
      land: 1
      SELF: 1 

  - type: REPLACE
    sampler:
      dimensions: 2
      type: DOMAIN_WARP
      amplitude: 40 
      warp:
        type: OPEN_SIMPLEX_2
        frequency: 0.005
      sampler:
        type: EXPRESSION
        expression: temperature(x, z)      
    from: _pot_rift
    range:
      min: ${customization.yml:biomeSpread.canyons.minY}
      max: 319
    to:
      _cold_canyon: 8
      land: 3
      _warm_canyon: 8