stages:
  #Perform cellular distribution to create zones where canyons will actually occur so they are not everywhere in the land-mass.
  - type: REPLACE_LIST
    sampler:
      dimensions: 2
      type: DOMAIN_WARP #Tried with A = 400, warp freq = 0.001, lots of overlap
      amplitude: 60 
      warp:
        type: OPEN_SIMPLEX_2
        frequency: 0.002
      sampler:
        type: CELLULAR
        return: CellValue
        frequency: 1 /  ${customization.yml:biomeSpread.regionDistance}
    from: land
    range:
      min: ${customization.yml:biomeSpread.canyons.minY}
      max: 319
    default-from: _warm_canyon
    default-to:
      - SELF: &CanyonDist     1
      - land: &LandDist       3
    to:
      _cold_canyon:
        - SELF: *CanyonDist
        - land: *LandDist