stages:
  #Distribute land into large temperature breaks to separate major canyon sections, since canyons changing vegitation mid trench is a little strange.
  - type: REPLACE
    sampler:
      type: EXPRESSION
      expression: if(((continentalRiverDist(x, z)>=1)&&(continents(x,z)>0.15)),1,-1)
    from: land
    range:
      min: ${customization.yml:biomeSpread.canyons.minY}
      max: 319
    to:
      land: 1
      _rift_land: 1
      
  #Perform cellular distribution to create zones where canyons will actually occur so they are not everywhere in the land-mass.
  - type: REPLACE
    sampler:
      dimensions: 2
      type: DOMAIN_WARP #Tried with A = 400, warp freq = 0.001, lots of overlap
      amplitude: 60 
      warp:
        type: OPEN_SIMPLEX_2
        frequency: 0.002
      sampler:
        type: EXPRESSION
        #Lower band is colder, upper band is warmer, white noise salted in randomizes placement.
        expression: floor(temperature(x,z)+noise(x,z)/2)
        samplers: 
          temperature: $math/samplers/rifts.yml:samplers.riftTemperature
          noise: $math/samplers/rifts.yml:samplers.riftRegions
    #from: land
    range:
      min: ${customization.yml:biomeSpread.canyons.minY}
      max: 319
    from: _rift_land
    to:
      _cold_rift: 0
      _cold_well: 10
      land: 1
      _warm_rift: 0
      _warm_well: 10

  - type: REPLACE_LIST
    sampler:
      type: EXPRESSION
      dimensions: 2
      variables:
        canyonStrength: ${customization.yml:biomeSpread.canyons.canyonAmount}
      expression: |
        min(max(-mask(x,z * 1.3) - canyonStrength, 0) * 18, 1) *
        max((-abs(base(x,z)) + 0.3) * 2, 0) * (1 / 0.2)
      samplers:
        base:
          dimensions: 2
          type: OPEN_SIMPLEX_2S
          frequency: 1 / ${customization.yml:biomeSpread.cellDistance} * 1
        mask:
          dimensions: 2
          type: CELLULAR
          frequency: 1 / ${customization.yml:biomeSpread.cellDistance} * 0.15
          seed: 23456345
    range:
      min: ${customization.yml:biomeSpread.canyons.minY}
      max: 319
    from: _warm_rift
    default-from: _warm_rift
    default-to: # 0 = outer, 1 = inner
      - land: &CanyonLandDist             16
      - SANDY_SPLITS: &CanyonFloorDist     9
    to: # 0 = outer, 1 = inner
      _cold_rift:
      - land: *CanyonLandDist
      - ICY_INCISIONS: *CanyonFloorDist
      
  #Perform cellular distribution to create zones where canyons will actually occur so they are not everywhere in the land-mass.
  - type: REPLACE_LIST
    sampler:
      dimensions: 2
      type: DOMAIN_WARP #Tried with A = 400, warp freq = 0.001, lots of overlap
      amplitude: 60 
      warp:
        type: OPEN_SIMPLEX_2
        frequency: 0.0002
      sampler: $math/samplers/rifts.yml:samplers.riftDistFromCenter
    range:
      min: ${customization.yml:biomeSpread.canyons.minY}
      max: 319
    default-from: _cold_well
    default-to:
      - SELF: &SinkholeSurrDist         1
      - SINKHOLE_FROZEN: &NotSinkholeLandDist     3
    to:
      _warm_well:
        - SELF: *SinkholeSurrDist
        - SINKHOLE_JUNGLE: *NotSinkholeLandDist
      
  #Further contain the canyons so that they are not on the edge of biomes borders (like an ocean, which is very strange)
  - type: REPLACE_LIST
    sampler:
      dimensions: 2
      type: EXPRESSION
      variables: 
        edgeThreshold: ${customization.yml:biomeSpread.borderBiomes.edgeThreshold}
      expression: if(cells(x,z) < -edgeThreshold, 1, -1)
      samplers:
        cells:
          dimensions: 2
          type: CELLULAR
          jitter: ${customization.yml:biomeSpread.cellJitter}
          frequency: 1 / ${customization.yml:biomeSpread.cellDistance}
    default-from: _cold_well
    default-to: # 0 = outer, 1 = inner
      - land: &SinkholeBorderDist     2
      - SINKHOLE_FROZEN: &SinkholeCentDist     1
    to: # 0 = outer, 1 = inner
      _warm_well:
        - land: *SinkholeBorderDist
        - SINKHOLE_JUNGLE: *SinkholeCentDist