#!/bin/bash

# ============================================================================
# check-biomes.sh
# Validates biome configurations and generates SuggestedImprovements.md
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="$REPO_ROOT/SuggestedImprovements.md"

cd "$REPO_ROOT"

biome_config_paths="$(find biomes/*/ -name "*.yml" -not -path "biomes/abstract/*" | sort)"

# Arrays to collect issues
declare -a missing_color_files=()
declare -a mismatch_files=()
declare -a mismatch_ids=()
declare -a mismatch_colors=()

color_key='color: \$biomes/colors.yml:'

for path in $biome_config_paths
do
    # Check if this is actually a biome file
    if ! grep -q "type: BIOME" "$path" 2>/dev/null; then
        continue
    fi

    config_id_line="$(grep -m1 'id: ' "$path")"
    config_id="${config_id_line#id: }"
    config_id="$(echo "$config_id" | tr -d '\r')"

    color_line="$(grep -m1 'color: ' "$path")"
    color_id="${color_line#$color_key}"
    color_id="$(echo "$color_id" | tr -d '\r')"

    if [[ $color_line != *$color_key* ]]; then
        missing_color_files+=("$path")
    elif [[ $color_id != $config_id ]]; then
        mismatch_files+=("$path")
        mismatch_ids+=("$config_id")
        mismatch_colors+=("$color_id")
    fi
done

# Count issues
missing_count=${#missing_color_files[@]}
mismatch_count=${#mismatch_files[@]}
total_count=$((missing_count + mismatch_count))

# Generate SuggestedImprovements.md
cat > "$OUTPUT_FILE" << 'HEADER'
# Suggested Improvements

This document lists configuration issues found during the biome validation audit. These should be reviewed and addressed to ensure consistency across all biome definitions.

HEADER

echo "## Summary" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "| Issue Type | Count |" >> "$OUTPUT_FILE"
echo "|------------|-------|" >> "$OUTPUT_FILE"
echo "| Missing valid color key | $missing_count |" >> "$OUTPUT_FILE"
echo "| Color reference mismatch | $mismatch_count |" >> "$OUTPUT_FILE"
echo "| **Total** | **$total_count** |" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [[ $total_count -eq 0 ]]; then
    echo "No issues found. All biome configurations are valid." >> "$OUTPUT_FILE"
    echo "SuggestedImprovements.md generated: 0 issues found"
    exit 0
fi

echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Missing color keys section
if [[ $missing_count -gt 0 ]]; then
    echo "## Missing Valid Color Key" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "These biome files do not contain a valid color key (expected format: \`color: \$biomes/colors.yml:BIOME_ID\`):" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "| File | Action Required |" >> "$OUTPUT_FILE"
    echo "|------|-----------------|" >> "$OUTPUT_FILE"

    for file in "${missing_color_files[@]}"; do
        echo "| \`$file\` | Add color key |" >> "$OUTPUT_FILE"
    done

    echo "" >> "$OUTPUT_FILE"
    echo "---" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
fi

# Color mismatch section
if [[ $mismatch_count -gt 0 ]]; then
    echo "## Color Reference Mismatches" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "These biome files have a color reference that does not match the biome ID:" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "| File | Biome ID | Current Color Reference |" >> "$OUTPUT_FILE"
    echo "|------|----------|------------------------|" >> "$OUTPUT_FILE"

    for i in "${!mismatch_files[@]}"; do
        echo "| \`${mismatch_files[$i]}\` | ${mismatch_ids[$i]} | ${mismatch_colors[$i]} |" >> "$OUTPUT_FILE"
    done

    echo "" >> "$OUTPUT_FILE"
    echo "---" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
fi

# Recommendations
cat >> "$OUTPUT_FILE" << 'RECOMMENDATIONS'
## Recommendations

### For Missing Color Keys
Add a color definition to each biome file in the format:
```yaml
color: $biomes/colors.yml:BIOME_ID
```
And ensure the corresponding color is defined in `biomes/colors.yml`.

### For Color Reference Mismatches
Two options:
1. **Option A**: Update the color reference to match the biome ID and add the new color to `biomes/colors.yml`
2. **Option B**: If intentionally reusing another biome's color, this may be acceptable for map visualization

---

*Generated by check-biomes.sh*
RECOMMENDATIONS

# Console output
echo "SuggestedImprovements.md generated: $total_count issues found"
echo "  - Missing color key: $missing_count"
echo "  - Color mismatch: $mismatch_count"

# Exit with warning (0) since issues are documented, not blocking error
exit 0
